#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sm-common-1.0.0
Version  : master
Release  : 1
URL      : https://github.com/openstack/stx-ha/archive/master.tar.gz
Source0  : https://github.com/openstack/stx-ha/archive/master.tar.gz
Summary  : Service Management Databases
Group    : Development/Tools
License  : Apache-2.0
Requires: sm-common-1.0.0-bin
Requires: sm-common-1.0.0-config
Requires: sm-common-1.0.0-lib
Requires: /bin/sh
Requires: mtce-pmon
Requires: sqlite-autoconf
Requires: systemd
Requires: util-linux
BuildRequires : buildreq-distutils3
BuildRequires : gcc
BuildRequires : glib-dev
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : sqlite-autoconf-dev
BuildRequires : systemd
BuildRequires : systemd-devel
BuildRequires : tox
BuildRequires : util-linux
BuildRequires : util-linux-dev
BuildRequires : virtualenv
Patch1: 0001-disable-warning-as-error.patch
Patch2: 0002-change-sysconfig-dir.patch

%description
Service Managment Databases

%package bin
Summary: bin components for the sm-common-1.0.0 package.
Group: Binaries
Requires: sm-common-1.0.0-config

%description bin
bin components for the sm-common-1.0.0 package.


%package config
Summary: config components for the sm-common-1.0.0 package.
Group: Default

%description config
config components for the sm-common-1.0.0 package.


%package dev
Summary: dev components for the sm-common-1.0.0 package.
Group: Development
Requires: sm-common-1.0.0-lib
Requires: sm-common-1.0.0-bin
Provides: sm-common-1.0.0-devel

%description dev
dev components for the sm-common-1.0.0 package.


%package lib
Summary: lib components for the sm-common-1.0.0 package.
Group: Libraries

%description lib
lib components for the sm-common-1.0.0 package.


%prep
%setup -q -n stx-ha-master
%patch1 -p1
%patch2 -p1

%build
## build_prepend content
VER=%{version}
MAJOR=`echo $VER | awk -F . '{print $1}'`
MINOR=`echo $VER | awk -F . '{print $2}'`
%global _buildsubdir %{_builddir}/stx-ha-master/service-mgmt/sm-common-1.0.0
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1537961392
pushd service-mgmt/sm-common-1.0.0
make  %{?_smp_mflags} VER=${VER} VER_MJR=$MAJOR
popd

%install
## install_prepend content
%global _unitdir '/usr/lib/systemd/system'
VER=%{version}
MAJOR=`echo $VER | awk -F . '{print $1}'`
MINOR=`echo $VER | awk -F . '{print $2}'`
## install_prepend end
export SOURCE_DATE_EPOCH=1537961392
rm -rf %{buildroot}
pushd service-mgmt/sm-common-1.0.0
make DEST_DIR=$RPM_BUILD_ROOT BIN_DIR=%{_bindir} UNIT_DIR=%{_unitdir} LIB_DIR=%{_libdir} INC_DIR=%{_includedir} VER=$VER VER_MJR=$MAJOR install_non_bb
popd
## install_append content
%global _sysconfdir '/usr/local/etc'
install -m 750 -d %{buildroot}/usr
install -m 750 -d %{buildroot}/usr/bin
install -m 750 -p -D %{_buildsubdir}/src/sm_eru %{buildroot}%{_bindir}/sm-eru
install -m 750 -p -D %{_buildsubdir}/src/sm_eru_dump %{buildroot}%{_bindir}/sm-eru-dump
install -m 750 -p -D %{_buildsubdir}/src/sm_watchdog %{buildroot}%{_bindir}/sm-watchdog
install -m 644 -p -D %{_buildsubdir}/scripts/sm-eru.service %{buildroot}%{_unitdir}/sm-eru.service
install -m 644 -p -D %{_buildsubdir}/scripts/sm-watchdog.service %{buildroot}%{_unitdir}/sm-watchdog.service
install -m 750 -d %{buildroot}%{_sysconfdir}/pmon.d
install -m 640 -p -D %{_buildsubdir}/scripts/sm-eru.conf %{buildroot}%{_sysconfdir}/pmon.d/sm-eru.conf
install -m 640 -p -D %{_buildsubdir}/scripts/sm-watchdog.conf %{buildroot}%{_sysconfdir}/pmon.d/sm-watchdog.conf
install -m 750 -p -D %{_buildsubdir}/scripts/sm-eru %{buildroot}%{_sysconfdir}/init.d/sm-eru
install -m 750 -p -D %{_buildsubdir}/scripts/sm-watchdog %{buildroot}%{_sysconfdir}/init.d/sm-watchdog
## install_append end

%files
%defattr(-,root,root,-)
/usr/local/etc/init.d/sm-eru
/usr/local/etc/init.d/sm-watchdog
/usr/local/etc/pmon.d/sm-eru.conf
/usr/local/etc/pmon.d/sm-watchdog.conf
/var/lib/sm/watchdog/modules/libsm_watchdog_nfs.so
/var/lib/sm/watchdog/modules/libsm_watchdog_nfs.so.master

%files bin
%defattr(-,root,root,-)
/usr/bin/sm-eru
/usr/bin/sm-eru-dump
/usr/bin/sm-watchdog

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/sm-eru.service
/usr/lib/systemd/system/sm-watchdog.service

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libsm_common.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libsm_common.so.master
